webtalk_init -webtalk_dir /home/jrvv/Prog_dir/study/FPGA_pract/fpga-pract-miet/lr2/LUT_and_FF/LUT_and_FF.sim/sim_1/behav/xsim/xsim.dir/tb_demo_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Feb 26 14:02:34 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "2493abca-fda4-49f1-92fe-97b32b405674" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "b52cb13b0c56460f9ab5869a100e0855" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "21" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 22.04.3 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2800.091 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "240 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "115444_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2523531099 -regid "" -xml /home/jrvv/Prog_dir/study/FPGA_pract/fpga-pract-miet/lr2/LUT_and_FF/LUT_and_FF.sim/sim_1/behav/xsim/xsim.dir/tb_demo_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/jrvv/Prog_dir/study/FPGA_pract/fpga-pract-miet/lr2/LUT_and_FF/LUT_and_FF.sim/sim_1/behav/xsim/xsim.dir/tb_demo_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/jrvv/Prog_dir/study/FPGA_pract/fpga-pract-miet/lr2/LUT_and_FF/LUT_and_FF.sim/sim_1/behav/xsim/xsim.dir/tb_demo_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
